### ISSUE TITLE
[FEAT]: Setup the project

### ISSUE THREAD

**Issue by krshkun** [krshkun/username-checker#1]
## Project Base

> I like new contributors to set up these applications because I already have done many, plus will help new contributors get a hand on Open Source

- [NextJS](https://nextjs.org/docs/api-reference/create-next-app): Use the create next CLI App, and generate a boiler plate: #2 
- [TailwindCSS](https://tailwindcss.com/docs/guides/nextjs): Setup TailwindCSS with Sass #3

## Open Source Best Practices

> For these, I generally just use the same files everywhere (for consistency), you can have a look at these, and add these files

- [Code Of Conduct](https://github.com/InnateComm/.github/blob/main/CODE_OF_CONDUCT.md) - Contributor Covenant Code of Conduct v2: #4
- [Contributing Guide](https://github.com/InnateComm/.github/blob/main/CONTRIBUTING.md) - Contributing guide template: #5
- [License](https://github.com/InnateComm/.github/blob/main/LICENSE) - MIT License : #6
- [Security Policy](https://github.com/InnateComm/.github/blob/main/SECURITY.md) - Informs users on how to report vulnerabilities : #6
- [Issue Templates](https://github.com/InnateComm/.github/tree/main/.github/ISSUE_TEMPLATE) - Basic Issue Templates: #7
- [PR Template](https://github.com/InnateComm/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md) - Fallback PR Template: #7

## Automation

> For automation, I don't really use much, but CI/CD, Stale and Changelog Release help automate common tasks

- [CI & CD](https://github.com/InnateComm/cruise-bot/blob/main/.github/workflows/nodejs.yml): #8
- [Stale](https://github.com/InnateComm/cruise-bot/blob/main/.github/workflows/stale.yml): #8
- [Changelog Release](https://github.com/InnateComm/cruise-bot/blob/main/.github/workflows/changelog.yml): #8

## Gitpodify

> You can have a read at https://www.gitpod.io/blog/gitpodify/ and gitpodify this project, feel free to ask for any help: #9

**Comment by krshdev** [comment]
I have linked all the work to be done, with the respective issue, you can link to that issue in your PR, and contribute, marking this as staff only, because this will be closed, once all of the above are done :)

**Comment by gptkrsh** [comment]
All of these issues have been taken care of
